import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "@/font/font";



export const metadata: Metadata = {
  title: "HealthCare",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="fr">
      <body className={`${roboto.className}`}>
        {children}
      </body>
    </html>
  );
}
